#Application Configuration
server:
 port: 8091

 # To See H2 Console in Browser
 # http://localhost:8091/h2-console
 # Enabling h2 console
spring:
  h2:
    console:
      enabled: true
    # =============
    # H2
    # =============
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password: 
    
 #================
 # JPA / HIBERNATE
 # ===============
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show-sql: true
        use-sql-comments: false
        format-sql: false
      
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"